name: firebase_with_bloc_or_cubit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  intl: ^0.19.0
  meta: ^1.16.0
  path_provider: ^2.1.5
  spider: ^4.2.2
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  easy_localization_generator: ^0.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - .env.dev
    - .env

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/sf_fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/sf_fonts/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/sf_fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/sf_fonts/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/sf_fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/sf_fonts/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/sf_fonts/SFProText-Bold.ttf
          weight: 700
        - asset: assets/sf_fonts/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/sf_fonts/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/sf_fonts/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/sf_fonts/SFProText-Light.ttf
          weight: 300
        - asset: assets/sf_fonts/SFProText-LightItalic.ttf
          weight: 300
          style: italic

# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  # Generates files with given ignore rules for file.
  # ignored_rules:
  #   - public_member_api_docs
  # Generates dart font family references for fonts specified in pubspec.yaml
  # fonts: true
  # -------- OR --------
  # fonts:
  #   class_name: MyFonts
  #   file_name: my_fonts
  # Location where all the generated references will be stored
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
