import 'package:go_router/go_router.dart';
import '../di_container/di_container.dart';
import '../../../features/auth/presentation/auth_bloc/auth_bloc.dart';
import '../../../features/profile/presentation/profile_page.dart';
import '../../../features/auth/presentation/sign_in/sign_in_page.dart';
import '../../../features/auth/presentation/sign_up/sign_up_page.dart';
import '../../layers_shared/presentation_layer_shared/pages_shared/change_password_page.dart';
import '../../layers_shared/presentation_layer_shared/pages_shared/_home_page.dart';
import '../../layers_shared/presentation_layer_shared/pages_shared/page_not_found.dart';
import '../../layers_shared/presentation_layer_shared/pages_shared/password_reset_page.dart';
import '../../layers_shared/presentation_layer_shared/pages_shared/splash_page.dart';
import '../../layers_shared/presentation_layer_shared/pages_shared/verify_email_page.dart';
import '../overlays/core/observers/overlay_navigation_observer.dart';
import 'widgets/app_scaffold.dart';
import 'utils/page_transition.dart';
import 'utils/router_redirect.dart';
import 'utils/router_refresher.dart' show GoRouterRefresher;

part 'routes_names.dart';
part 'router.dart';
